### ISSUE TITLE
"Should have a Title" check is misleading

### ISSUE THREAD

**Issue by tollmanz** [CondeNast/opensource-check#1]
## Expected Behavior

The "Should have a Title" check should fail if and only if no title is present.

## Current Behavior

The "Should have a Title" check will fail when README.md has a title, but it does not match the package name.

## Possible Solution

"Should have a Title should only check for presence of a title. Another check for "Should use same title for README.md and package.json" should be added to ensure the two titles match.

## Steps to Reproduce (for bugs)

1. Create a README.md with a title `Test`
2. Create a package.json with name, `foo`
3. Notice the failing test

## Context

This affected me as I couldn't understand why this test was failing. I had a title in my README.md. I had to look at the code to see why it was failing. Being more clear about why the failure occurred with improve the speed with which a dev can act on the advice.

## Your Environment
* Version used: 0.0.1

**Comment by gautamarora** [comment]
Thanks for sharing your feedback @tollmanz.

`Should have Package Name as Title` is certainly clearer and the reason the check is in place. Thoughts?

**Comment by tollmanz** [comment]
@gautamarora WFM. Clears up the initial issue.
