### ISSUE TITLE
Unable to use when installed globally

### ISSUE THREAD

**Issue by pgoldrbx** [CondeNast/opensource-check#4]
After following the docs and installing globally, I'm getting errors when trying to use this tool.

## Expected Behavior

Tool should evaluate project

## Current Behavior
Tool reports a Jest error

## Steps to Reproduce (for bugs)

```sh
$ npm i -g @condenast/opensource-check
$ opensource-check --path ./my-project
No tests found
No files found in /Users/pgold/.nvm/versions/node/v8.9.4/lib/node_modules/@condenast/opensource-check.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches
```

## Your Environment

* Version used: 0.0.1-5
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v8.9.4 and npm 5.8.0
* Operating System and version (desktop or mobile): OS X
* Link to your project: https://github.com/CondeNast/jsonml.js

**Comment by kristakhare** [comment]
I'm having the same issue, but with all three usage options, not just the global dependency. 
Windows 10, Node.js 8.11.1, npm 5.10.0

**Comment by gautamarora** [comment]
sorry about this, i will work on fix this week.

Here is a workaround in the time being to install using git:
```
git clone https://github.com/CondeNast/opensource-check.git
npm install -g opensource-check/
```

**Comment by kristakhare** [comment]
Thanks so much @gautamarora - that worked. And thanks for this handy tool!

**Comment by gautamarora** [comment]
awesome! thanks for trying it out 🙌

**Comment by pgoldrbx** [comment]
I've been debugging and I've made it pretty far. The issue is ultimately this: within `jest-cli`, the library collects a list of files from the file system into a [`HasteFS`](https://github.com/facebook/jest/blob/3ce87434570d23be061648162488ca5599e40651/packages/jest-haste-map/src/haste_fs.js) instance. This project is installed as a node module, no files are loaded from the filesystem. After some experimentation, I realized that the tool succeeds _unless_ nested under a `node_modules` path.

For example, we know that cloning the repo and using it locally will work fine.
```js
git clone git@github.com:CondeNast/opensource-check.git
cd opensource-check && npm i && cd -
./opensource-check/bin/index.js --path my-project
```
If we move the project underneath a `node_modules` directory, everything fails.

This tells me that the haste map, looking for project files to test, is ignoring `node_modules` by default - which is sensible if running jest directly within a project. _however_ we need to create an exception somehow. I have to dig further into the code to sort this out but it's not the easiest to trace.

**Comment by gautamarora** [comment]
Yes! You’re on the right track for this.

**Comment by pgoldrbx** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

_sooooo_

I just did a clean global install of this module. And now things appear to work. It's possible that there was a bug or an issue already resolved in one of the `jest` modules. Can anyone reproduce that this works now?

**Comment by stripethree** [comment]
No dice for me. I tried with node v8.11.2 and v8.9.2, same error with both after clean global installs.

**Comment by stripethree** [comment]
Not sure if this is relevant, but I noticed this while running it from a checkout.

```
➜  opensource-check git:(master) ./bin/index.js --path ~/Work/launch-vehicle-fbm
...
ENOENT: no such file or directory, open 'undefined/package.json'
```
That _undefined_ is suspicious.

Freaky... I run that same command again with the absolute path, it's fine. Then tried it again with the original `~` path, and it works.

**Comment by gautamarora** [comment]
@pgoldrbx @stripethree - i'll try to take a look at this again to see how to fix the global module installation issue. From what i remember in my past experiments, the times that it worked was having it installed via git clone and not npm global install.

**Comment by stripethree** [comment]
```
➜  ~ npm i -g @condenast/opensource-check
➜  ~ opensource-check --version
0.0.2
➜  ~ opensource-check --path ./Work/launch-vehicle-fbm 
 PASS  .nvm/versions/node/v8.11.2/lib/node_modules/@condenast/opensource-check/__checks__/docs.test.js
...
Test Suites: 2 passed, 2 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time:        0.387s, estimated 1s
Ran all test suites.
```

✅
